---
# tasks file for minecraft_java_deploy

- name: Create Folders
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: "0775"
  with_items:
    - "{{ minecraft_install_path }}"

# FIXME
# - name: Modify firewalld configuration for bedrock server ports
#   ansible.posix.firewalld:
#     port: item
#     permanent: yes
#     state: enabled
#   with_items:
#     - "{{ server_port }}/udp"
#     - "{{ ipv6_server_port }}/udp"
#   when: ansible_os_family == 'RedHat'

- name: Create minecraft service
  template:
    src: templates/minecraft_service.j2
    dest: "/etc/systemd/system/{{ minecraft_server_name }}_minecraft.service"
    mode: +x
  register: create_service

- name: Create server start script
  template:
    src: templates/minecraft_service_script.j2
    dest: "{{ minecraft_install_path }}start_{{ minecraft_server_name }}_minecraft.sh"
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: +x

- name: reload systemd
  command: systemctl daemon-reload
  when: create_service.changed

- name: Download Minecraft Java Server
  get_url:
    url: "{{ java_url }}"
    dest: "{{ minecraft_install_path }}"

- name: Set EULA
  template:
    src: templates/eula.j2
    dest: "{{ minecraft_install_path }}eula.txt"

- name: Set Server.Properties file
  template:
    src: templates/server_properties.j2
    dest: "{{ minecraft_install_path }}server.properties"
    owner: "{{ service_account }}"
    group: "{{ service_account }}"

- name: Accept EULA
  lineinfile:
    path: "{{ eula_file }}"
    regexp: "^eula="
    line: "eula=true"

- name: Template permissions.json file
  template:
    src: templates/permissions.json.j2
    dest: "{{ unpack_dir }}permissions.json"
  when:
    - account_permissions is defined

- name: Template whitelist.json file
  template:
    src: templates/whitelist.json.j2
    dest: "{{ unpack_dir }}/whitelist.json"
  when:
    - whitelist_accounts is defined

- name: reload systemd
  command: systemctl daemon-reload
  when: create_service.changed

- name: Set permissions
  file:
    path: "{{ minecraft_install_path }}"
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: u=rwx,g=rwx,o=rx
    recurse: true

- name: Start new minecraft service
  service:
    name: "{{ minecraft_service_name }}"
    enabled: true
    state: started
