---
- name: Set level name
  lineinfile:
    path: "{{ server_properties_file }}"
    regexp: "^level-name="
    line: "level-name={{ level_name }}"

- name: Set max-players
  lineinfile:
    path: "{{ server_properties_file }}"
    regexp: "^max-players="
    line: "max-players={{ max_players }}"

- name: Set gamemode
  lineinfile:
    path: "{{ server_properties_file }}"
    regexp: "^gamemode="
    line: "gamemode={{ gamemode }}"

- name: Set difficulty
  lineinfile:
    path: "{{ server_properties_file }}"
    regexp: "^difficulty="
    line: "difficulty={{ minecraft_server_name }}"

- name: Set online-mode
  lineinfile:
    path: "{{ server_properties_file }}"
    regexp: "^online-mode="
    line: "online-mode={{ online_mode }}"

- name: Set whitelist on/off
  lineinfile:
    path: "{{ server_properties_file }}"
    regexp: "^white-list="
    line: "white-list={{ whitelist }}"

- name: PvP On or Off
  lineinfile:
    path: "{{ server_properties_file }}"
    regexp: "^pcp="
    line: "pcp={{ pvp_onoff }}"

- name: Set server port
  lineinfile:
    path: "{{ server_properties_file }}"
    regexp: "^server-port="
    line: "server-port={{ server_port }}"

- name: Set server remote console port
  lineinfile:
    path: "{{ server_properties_file }}"
    regexp: "^rcon.port="
    line: "rcon.port={{ rcon_port }}"

- name: Set server remote console password
  lineinfile:
    path: "{{ server_properties_file }}"
    regexp: "^rcon.password="
    line: "rcon.password={{ rcon_password }}"
  no_log: true

- name: Set Message of the day
  lineinfile:
    path: "{{ server_properties_file }}"
    regexp: "^motd="
    line: "motd={{ message_otd }}"

- name: Set level seed
  lineinfile:
    path: "{{ server_properties_file }}"
    regexp: "^level-seed="
    line: "level-seed={{ level_seed }}"
  when: level_seed is defined
